version: '3'

services:
   livraria_database:
    image: mysql:8.0
    restart: always
    expose:
 
     - 3306

    env_file:
     - livraria-online_database.env

   livraria_app:
    image: alura/livraria-api
    restart: always
    ports: 
     - 8001:8001

    depends_on: 
     - livraria_database
    env_file:
     - livraria-online.env


